app = angular.module 'stanfordViz'

app.factory 'events', ->
  # Temporary hacky hack
  return {
    show: true,
    items: {
      '1963': ['I have a dream']
      '1964': ['US bombs Vietnam']
      '1965': ['Vietnam War', ['history', 'polisci']]
      '1966': ['Star Trek premieres']
      '1967': ['Six-Day War']
      '1968': ['Intel founded', ['ee']]
      '1969': ['Moon landing']
      '1970': ['First 747 commercial flight']
      '1971': ['Stanford prison experiment', ['psych']]
      '1972': ['The Godfather premieres']
      '1973': ['Oil shock', ['chemeng']]
      '1974': ['Watergate']
      '1975': ['Microsoft founded']
      '1976': ['Apple founded', ['ee']]
      '1977': ['World Trade Center completed']
      '1978': ['Space Invaders']
      '1979': ['Ayatollah\'s in Iran']
      '1980': ['Iran-Iraq War']
      '1981': ['MS-DOS released']
      '1982': ['First CD player', ['ee']]
      '1983': ['Sally Ride']
      '1984': ['Reagan re-elected', ['econ', 'polisci']]
      '1985': ['First .com domain']
      '1986': ['Chernobyl disaster']
      '1987': ['Tear down this wall']
      '1988': ['First transatlantic fibre optic cable']
      '1989': ['Berlin wall']
      '1990': ['Gulf War']
      '1991': ['End of Soviet Union', ['history', 'polisci']]
      '1992': ['Linux released under GNU']
      '1993': ['First Chipotle']
      '1994': ['Netscape founded']
      '1995': ['Amazon.com online']
      '1996': ['Dolly the sheep', ['bio']]
      '1997': ['Hong Kong returned']
      '1998': ['Google founded']
      '1999': ['MS&E department formed', ['ms&e', 'ie', 'opsres']]
      '2000': ['Dot-com burst', ['cs', 'econ', 'symsys']]
      '2001': ['9/11 terrorist attacks']
      '2002': ['War in Afghanistan']
      '2003': ['Invasion of Iraq', ['polisci']]
      '2004': ['Facebook launches']
      '2005': ['Hurricane Katrina']
      '2006': ['North Korean nukes']
      '2007': ['iPhone released']
      '2008': ['Lehman Brothers bankrupted']
      '2009': ['CS revamps curriculum', ['cs']]
      '2010': ['WikiLeaks cables']
      '2011': ['Fukushima earthquake']
      '2012': ['Facebook IPOs']
    }
  }